name: 'Terraform operations'
description: 'Runs Terraform setup and operations'
inputs:
  flow:
    description: 'This identifies whether it is a PR flow or Push flow'
    required: true
    default: plan
  working_dir:
    description: 'Working Directory for terraform commands'
    required: true
runs:
  using: composite
  steps:
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: "~1.12.0"
  - name: Initialize Terraform
    run: terraform init
    working-directory: ${{ inputs.working_dir }}
  - name: Check format
    run: terraform fmt -check -recursive
    working-directory: ${{ inputs.working_dir }}
  - name: Validate Terraform
    run: terraform validate
    working-directory: ${{ inputs.working_dir }}
  - name: Run Plan (PR)
    if: ${{ inputs.flow }} == 'plan'
    run: terraform plan
    working-directory: ${{ inputs.working_dir }}
  - name: Run Plan (Push)
    if: ${{ inputs.flow }} == 'push'
    run: terraform plan -out oidc-plan.tfplan
    working-directory: ${{ inputs.working_dir }}
  - name: Run Apply
    if: ${{ inputs.flow }} == 'push'
    run: terraform apply -input=false oidc-plan.tfplan
    working-directory: ${{ inputs.working_dir }}
    
    