name: 'Terraform operations'
description: 'Runs Terraform setup and operations'
inputs:
  flow:
    description: 'This identifies whether it is a PR flow or Push flow'
    required: true
    default: plan
  working_dir:
    description: 'Working Directory for terraform commands'
    required: true
runs:
  using: composite
  steps:
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: "~1.12.0"
  - name: Initialize Terraform
    run: |
      cd ${{ inputs.working_dir }}
      terraform init
    shell: bash 
  - name: Check format
    run: |
      cd ${{ inputs.working_dir }}
      terraform fmt -check -recursive
    shell: bash
  - name: Validate Terraform
    run: |
      cd ${{ inputs.working_dir }}
      terraform validate
    shell: bash
  - name: Run Plan (PR)
    run: |
      if [ "${{ inputs.flow }}" = "plan" ]; then
        cd ${{ inputs.working_dir }}
        terraform plan -input=false
      fi
    shell: bash
  - name: Run Plan (Push)
    run: |
      if [ "${{ inputs.flow }}" = "push" ]; then
        cd ${{ inputs.working_dir }}
        terraform plan -input=false -out oidc-plan.tfplan
      fi
    shell: bash
  - name: Run Apply
    run: |
      if [ "${{ inputs.flow }}" = "push" ]; then
        cd ${{ inputs.working_dir }}
        terraform apply -input=false oidc-plan.tfplan
      fi
    shell: bash
    
    