name: 'Terraform operations'
description: 'Runs Terraform setup and operations'
inputs:
  flow:
    description: 'This identifies whether it is a PR flow or Push flow'
    required: true
    default: plan
runs:
  using: composite
  steps:
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3
    with:
      terraform_version: "~1.12.0"
  - name: Initialize Terraform
    run: terraform init
  - name: Check format
    run: terraform fmt -check -recursive
  - name: Validate Terraform
    run: terraform validate
  - name: Run Plan (PR)
    if: ${{ inputs.flow }} == 'plan'
    run: terraform plan
  - name: Run Plan (Push)
    if: ${{ inputs.flow }} == 'push'
    run: terraform plan -out oidc-plan.tfplan
  - name: Run Apply
    if: ${{ inputs.flow }} == 'push'
    run: terraform apply -input=false oidc-plan.tfplan
    
    