name: App Hosting 80 Push Action
on:
  push:
    branches:
    - main
    paths:
    - 'ec2-app-hosting-80/**'
    - '.github/workflows/app-hosting-80-push.yaml'
    - '!**/*.md'

permissions:
  id-token: write
  contents: read

jobs:
  terraform_processing:
    uses: ./.github/workflows/terraform-plan-apply.yaml
    with:
      flow: push
      working_dir: ec2-app-hosting-80
      ips: ${{ vars.WHITELISTED_IPS }} 
    secrets:
      ROLE: ${{ secrets.PUSH_ACTION_ROLE }} 
  