name: DR Push Action
on:
  push:
    branches:
    - main
    paths:
    - 'DR-scenario/**'
    - '.github/workflows/dr-scenario-80-push.yaml'
    - '!**/*.md'

permissions:
  id-token: write
  contents: read

jobs:
  terraform_processing_base:
    uses: ./.github/workflows/terraform-plan-apply.yaml
    with:
      flow: push
      working_dir: DR-scenario/BaseSetup
      ips: ${{ vars.WHITELISTED_IPS }}
    secrets:
      ROLE: ${{ secrets.PUSH_ACTION_ROLE }}
  terraform_processing_ec2_attachment:
    needs: terraform_processing_base
    uses: ./.github/workflows/terraform-plan-apply.yaml
    with:
      flow: push
      working_dir: DR-scenario/EC2Attachment
      ips: ${{ vars.WHITELISTED_IPS }}
    secrets:
      ROLE: ${{ secrets.PUSH_ACTION_ROLE }}
