name: 'Terraform operations'
on:
  workflow_call:
    inputs:
      flow:
        description: 'This identifies whether it is a PR flow or Push flow'
        required: true
        type: string
      working_dir:
        description: 'Working Directory for terraform commands'
        required: true
        type: string
    secrets:
      ROLE: 
        required: true
jobs:
  terraform_operations:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_dir }}
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ROLE }}
        aws-region: "ap-south-1"
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "~1.12.0"
    - name: Initialize Terraform
      run: terraform init
    - name: Check format
      run: terraform fmt -check -recursive
    - name: Validate Terraform
      run: terraform validate
    - name: Run Plan - PR
      if: ${{ inputs.flow == 'plan' }}
      run: terraform plan -input=false
    - name: Run Plan - Push
      if: ${{ inputs.flow == 'push' }}
      run: terraform plan -input=false -out oidc-plan.tfplan
    - name: Run Apply
      if: ${{ inputs.flow == 'push' }}
      run: terraform apply -input=false oidc-plan.tfplan
